"""Add file_data and image_data to Music model

Revision ID: 5dba23cf95e7
Revises: 85f586bd4d60
Create Date: 2024-06-29 21:24:18.938112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dba23cf95e7'
down_revision = '85f586bd4d60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('music', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_data', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('image_data', sa.LargeBinary(), nullable=True))
        batch_op.drop_column('file')
        batch_op.drop_column('image')

    with op.batch_alter_table('playlist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_image_data', sa.LargeBinary(), nullable=True))
        batch_op.drop_column('cover_image')

    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_image', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_column('cover_image_data')

    with op.batch_alter_table('music', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('file', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
        batch_op.drop_column('image_data')
        batch_op.drop_column('file_data')

    # ### end Alembic commands ###
